(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();const c=document.querySelector("#task-form"),l=document.querySelector(".theme-toggle-button"),i=document.querySelector(".tasks-list");function d(t){const e=JSON.parse(localStorage.getItem("tasks"))||[];e.push(t),localStorage.setItem("tasks",JSON.stringify(e))}function m(t){const o=(JSON.parse(localStorage.getItem("tasks"))||[]).filter((a,s)=>s!==t);localStorage.setItem("tasks",JSON.stringify(o))}function u(){const e=(JSON.parse(localStorage.getItem("tasks"))||[]).map(({title:o,description:a})=>`<li class="task-list-item">
        <button class="task-list-item-btn">Delete</button>
        <h3>${o}</h3>
        <p>${a}</p>
      </li>`).join("");i.insertAdjacentHTML("beforeend",e)}function f({title:t,description:e}){const o=`<li class="task-list-item">
        <button class="task-list-item-btn">Delete</button>
        <h3>${t}</h3>
        <p>${e}</p>
      </li>`;i.insertAdjacentHTML("beforeend",o)}u();c.addEventListener("submit",t=>{t.preventDefault();const e=t.target.taskName.value.trim(),o=t.target.taskDescription.value.trim();if(console.log(e),console.log(o),!e||!o)return alert("Заповніть всі поля форми");f({title:e,description:o}),d({title:e,description:o}),c.reset()});i.addEventListener("click",t=>{if(t.target.classList.contains("task-list-item-btn")){const e=t.target.closest(".task-list-item");console.log(e);const o=[...i.children].indexOf(e);m(o),e.remove()}});l.addEventListener("click",t=>{const e=document.querySelector("body");e.classList.contains("theme-dark")?(e.classList.replace("theme-dark","theme-light"),localStorage.setItem("theme","theme-light")):(e.classList.replace("theme-light","theme-dark"),localStorage.setItem("theme","theme-dark"))});window.addEventListener("DOMContentLoaded",()=>{const t=localStorage.getItem("theme"),e=document.querySelector("body");t&&(e.classList.remove("theme-dark","theme-light"),e.classList.add(t))});
//# sourceMappingURL=index.js.map
