(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const c=document.querySelector("#task-form"),l=document.querySelector(".theme-toggle-button"),i=document.querySelector(".tasks-list");function m(s){const t=JSON.parse(localStorage.getItem("tasks"))||[];t.push(s),localStorage.setItem("tasks",JSON.stringify(t))}function u(s){const o=(JSON.parse(localStorage.getItem("tasks"))||[]).filter((a,e)=>e!==s);localStorage.setItem("tasks",JSON.stringify(o))}function d(){const t=(JSON.parse(localStorage.getItem("tasks"))||[]).map(({title:o,description:a})=>`<li class="task-list-item">
        <button class="task-list-item-btn">Delete</button>
        <h3>${o}</h3>
        <p>${a}</p>
      </li>`).join("");i.insertAdjacentHTML("beforeend",t)}function f({title:s,description:t}){const o=`<li class="task-list-item">
        <button class="task-list-item-btn">Delete</button>
        <h3>${s}</h3>
        <p>${t}</p>
      </li>`;i.insertAdjacentHTML("beforeend",o)}d();c.addEventListener("submit",s=>{s.preventDefault();const t=s.target.taskName.value.trim(),o=s.target.taskDescription.value.trim();if(console.log(t),console.log(o),!t||!o)return alert("Заповніть всі поля форми");f({title:t,description:o}),m({title:t,description:o}),c.reset()});i.addEventListener("click",s=>{if(s.target.classList.contains("task-list-item-btn")){const t=s.target.closest(".task-list-item");console.log(t);const o=[...i.children].indexOf(t);u(o),t.remove()}});l.addEventListener("click",s=>{const t=document.querySelector("body");t.classList.contains("theme-dark")?(t.classList.replace("theme-dark","theme-light"),localStorage.setItem("theme","theme-light")):(t.classList.replace("theme-light","theme-dark"),localStorage.setItem("theme","theme-dark"))});
//# sourceMappingURL=index.js.map
